doc-warnings: yes
strictness: high
max-line-length: 80
pep8:
    full: true
pylint:
    disable:
      - bad-whitespace
      - invalid-name
      - missing-super-argument
      - old-style-class
      - superfluous-parens
